name: emphaticpuma.github.io

description: emphaticpuma's region of the internet

url: http://emphaticpuma.github.io

permalink: pretty

markdown: rdiscount

excerpt_separator: <!--excerpt_separator-->

highlighter: pygments

exclude: [README.md, package.json, Gruntfile.js, node_modules]