name: emphaticpuma.github.io

desc: emphaticpuma's region of the internet

url: http://emphaticpuma.github.io

permalink: /:month-:day-:year/:title.html 

markdown: kramdown

kramdown:
    smart_quotes: ['lsquo','rsquo','ldquo','rdquo']

excerpt_separator: <!--excerpt_separator-->

highlighter: pygments

exclude: ['README.md', 'package.json', 'Gruntfile.js', 'node_modules', 'bower_components/']
